language: go

go: 
  - 1.14.x

env:
  - GO111MODULE=on

addons:
  hosts:
    - mysql.a
    - redis.a

service:
  - mysql
  - redis-server

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS authenticator;'

before_script:
  - echo "CREATE USER 'auth'@'localhost' IDENTIFIED BY '123456';\nGRANT ALL ON authenticator.* TO 'auth'@'localhost';\nFLUSH PRIVILEGES;\n" | mysql -u root

script: 
  - go build