version: "3.7"

services:

  redis:
    image: redis:alpine
    ports:
    - 6379:6379
    networks: 
      new:
        aliases:
        - redis.a

  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: auth
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: authenticator
    ports: 
    - 3306:3306
    networks: 
      new:
        aliases: 
        - mysql.a

  auth:
    depends_on:
    - redis
    - mysql
    image: ubuntu
    restart: always
    volumes: 
    - ./:/auth
    ports:
    - 9990:9990
    networks:
      new:
    command: 
    - /bin/sh
    - -c 
    - |
      /auth/authenticator -c /auth/auth.simple.yml

networks:
  new:
